#!/usr/bin/env python3
"""
waybar-theme-sync: Dynamic Palette Synchronization Engine for Waybar & Wofi.
Reads colors.toml / terminal palettes and auto-generates matching CSS variables.
"""

import argparse
import os
import re
import subprocess
import sys
import time

DEFAULT_COLORS = {
    "background": "#1a1b26",
    "dark_background": "#16161e",
    "foreground": "#c0caf5",
    "accent": "#7aa2f7",
    "muted": "#565f89",
    "red": "#f7768e",
    "green": "#9ece6a",
    "yellow": "#e0af68",
    "blue": "#7aa2f7",
    "magenta": "#bb9af7",
    "cyan": "#7dcfff",
}


def hex_to_rgba(hex_code: str, alpha: float = 0.8) -> str:
    cleaned = hex_code.lstrip("#")
    if len(cleaned) == 6:
        r = int(cleaned[0:2], 16)
        g = int(cleaned[2:4], 16)
        b = int(cleaned[4:6], 16)
        return f"rgba({r}, {g}, {b}, {alpha})"
    return f"rgba(26, 27, 38, {alpha})"


def parse_toml_colors(file_path: str) -> dict:
    colors = DEFAULT_COLORS.copy()
    if not os.path.exists(file_path):
        return colors

    with open(file_path, "r", encoding="utf-8") as f:
        for line in f:
            m = re.match(r'^([a-zA-Z0-9_]+)\s*=\s*["\']([^"\']+)["\']', line.strip())
            if m:
                colors[m.group(1)] = m.group(2)
    return colors


def generate_waybar_css(colors: dict, opacity: float = 0.8) -> str:
    bg = colors.get("dark_background", colors.get("background", "#1a1b26"))
    fg = colors.get("foreground", "#c0caf5")
    accent = colors.get("accent", colors.get("blue", "#7aa2f7"))
    muted = colors.get("muted", "#565f89")
    bg_rgba = hex_to_rgba(bg, opacity)
    accent_border = hex_to_rgba(accent, 0.3)

    return f"""/* Auto-generated by waybar-theme-sync */
@define-color bg {bg_rgba};
@define-color fg {fg};
@define-color accent {accent};
@define-color muted {muted};
@define-color border {accent_border};
@define-color red {colors.get("red", "#f7768e")};
@define-color green {colors.get("green", "#9ece6a")};
@define-color yellow {colors.get("yellow", "#e0af68")};
@define-color blue {colors.get("blue", "#7aa2f7")};
@define-color magenta {colors.get("magenta", "#bb9af7")};
@define-color cyan {colors.get("cyan", "#7dcfff")};
"""


def reload_waybar():
    try:
        subprocess.run(["pkill", "-SIGUSR2", "waybar"], check=False)
        print("✔ Waybar reloaded via SIGUSR2")
    except Exception as e:
        print(f"Failed to reload Waybar: {e}", file=sys.stderr)


def run_sync(input_path: str, output_path: str, opacity: float, reload: bool):
    colors = parse_toml_colors(input_path)
    css = generate_waybar_css(colors, opacity)

    os.makedirs(os.path.dirname(os.path.abspath(output_path)), exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        f.write(css)

    print(f"✔ Palette generated: {output_path} (accent: {colors.get('accent')})")

    if reload:
        reload_waybar()


def main():
    parser = argparse.ArgumentParser(
        description="Sync Waybar styles dynamically with TOML color palettes."
    )
    parser.add_argument(
        "-i",
        "--input",
        default=os.path.expanduser("~/.local/state/omarchy/current/theme/colors.toml"),
        help="Path to colors.toml (default: ~/.local/state/omarchy/current/theme/colors.toml)",
    )
    parser.add_argument(
        "-o",
        "--output",
        default=os.path.expanduser("~/.config/waybar/colors.css"),
        help="Target output CSS file (default: ~/.config/waybar/colors.css)",
    )
    parser.add_argument(
        "--opacity",
        type=float,
        default=0.8,
        help="Background transparency alpha (0.0 to 1.0, default 0.8)",
    )
    parser.add_argument(
        "-r",
        "--reload",
        action="store_true",
        help="Automatically trigger SIGUSR2 to live-reload Waybar",
    )
    parser.add_argument(
        "-w",
        "--watch",
        action="store_true",
        help="Watch input file and continuously sync on change",
    )

    args = parser.parse_args()

    run_sync(args.input, args.output, args.opacity, args.reload)

    if args.watch:
        print(f"👀 Watching {args.input} for changes...")
        last_mtime = os.path.getmtime(args.input) if os.path.exists(args.input) else 0
        try:
            while True:
                time.sleep(1.5)
                if os.path.exists(args.input):
                    mtime = os.path.getmtime(args.input)
                    if mtime != last_mtime:
                        last_mtime = mtime
                        run_sync(args.input, args.output, args.opacity, args.reload)
        except KeyboardInterrupt:
            print("\nStopped watcher.")


if __name__ == "__main__":
    main()
